version: '3.3'
services:
    auth:
        image: node:current-slim
        working_dir: /backend/services
        volumes:
            - ./backend/package.json:/backend/package.json
            - ./backend/services:/backend/services
        command: bash -c "npm install && node auth.js"
        ports:
            - '5000:5000'

    inventory:
        image: node:current-slim
        working_dir: /backend/services
        volumes:
            - ./backend/package.json:/backend/package.json
            - ./backend/services:/backend/services
        command: bash -c "npm install && node inventory.js"
        ports:
            - '5001:5001'

    cart:
        image: node:current-slim
        working_dir: /backend/services
        volumes:
            - ./backend/package.json:/backend/package.json
            - ./backend/services:/backend/services
        command: bash -c "npm install && node cart.js"
        ports:
            - '5002:5002'
    
